# Generated by Django 4.2.7 on 2024-03-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_slug_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
