name: Quality Assurance

on: [push, workflow_call]

jobs:

  quality-assurance-assertion:
    name: Quality Assurance Code Valuation


    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macOS-latest]
    #   python-version: [3.6, 3.7, 3.8,3.9, 3.10, 3.11, 3.12]

    container: python:3.9

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Server
        run: echo Hello world
