name: Quality Assurance

on: [push, workflow_call]

jobs:

  quality-assurance-assertion:
    name: Quality Assurance Code Valuation


    runs-on: ubuntu-latest
    container: python:3.9

    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_USER: kwasa
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: alvan

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -rP
